#project
project:
  name: mall #项目名称
  port: :8102 #端口
  env: local #本地：local 测试：develop 线上：production

#mysql
mysql:
  host: localhost
  port: :3306
  database: mall
  username: root
  password: root
  log: true

#redis
redis:
  host: localhost
  port: :6379
  database: 1
  username:
  password:
